name    'dwhatmuff-logindefs'
version '0.1.0'
source 'github.com/danielwhatmuff/dwhatmuff-logindefs'
author 'dwhatmuff'
license 'Apache License, Version 2.0'
summary 'dwhatmuff-logindefs'
description 'Module to manage the login.defs configuration'
project_page 'github.com/danielwhatmuff/dwhatmuff-logindefs'

dependency 'puppetlabs/stdlib', '>= 4.6.0'
